// <auto-generated />
using System;
using ManageSchoolScore.DatabaseContextMSS;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ManageSchoolScore.Migrations
{
    [DbContext(typeof(DBContextMSS))]
    [Migration("20240121200850_ChangeField")]
    partial class ChangeField
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ManageSchoolScore.Models.SchoolYear", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("ExamYear")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SchoolYears");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            ExamYear = 2017,
                            Name = "2017",
                            Status = ""
                        },
                        new
                        {
                            Id = 2L,
                            ExamYear = 2018,
                            Name = "2018",
                            Status = ""
                        },
                        new
                        {
                            Id = 3L,
                            ExamYear = 2019,
                            Name = "2019",
                            Status = ""
                        },
                        new
                        {
                            Id = 4L,
                            ExamYear = 2020,
                            Name = "2020",
                            Status = ""
                        },
                        new
                        {
                            Id = 5L,
                            ExamYear = 2021,
                            Name = "2021",
                            Status = ""
                        },
                        new
                        {
                            Id = 6L,
                            ExamYear = 2022,
                            Name = "2022",
                            Status = ""
                        },
                        new
                        {
                            Id = 7L,
                            ExamYear = 2023,
                            Name = "2023",
                            Status = ""
                        },
                        new
                        {
                            Id = 8L,
                            ExamYear = 2024,
                            Name = "2024",
                            Status = ""
                        });
                });

            modelBuilder.Entity("ManageSchoolScore.Models.Score", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<double>("ScoreInDecimal")
                        .HasColumnType("float");

                    b.Property<long>("StudentId")
                        .HasColumnType("bigint");

                    b.Property<long>("SubjectId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.HasIndex("SubjectId");

                    b.ToTable("Scores");
                });

            modelBuilder.Entity("ManageSchoolScore.Models.Student", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("SchoolYearId")
                        .HasColumnType("bigint");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SchoolYearId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("ManageSchoolScore.Models.StudentRaw", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double?>("Biology")
                        .HasColumnType("float");

                    b.Property<double?>("Chemistry")
                        .HasColumnType("float");

                    b.Property<double?>("CivicEducation")
                        .HasColumnType("float");

                    b.Property<double?>("CombinedNaturalSciences")
                        .HasColumnType("float");

                    b.Property<double?>("CombinedSocialSciences")
                        .HasColumnType("float");

                    b.Property<double?>("English")
                        .HasColumnType("float");

                    b.Property<double?>("Geography")
                        .HasColumnType("float");

                    b.Property<double?>("History")
                        .HasColumnType("float");

                    b.Property<double?>("Literature")
                        .HasColumnType("float");

                    b.Property<double?>("Mathematics")
                        .HasColumnType("float");

                    b.Property<double?>("Physics")
                        .HasColumnType("float");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("YearNow")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("StudentCsvs");
                });

            modelBuilder.Entity("ManageSchoolScore.Models.Subject", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Subjects");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Code = "MATH",
                            Name = "Toán"
                        },
                        new
                        {
                            Id = 2L,
                            Code = "LIT",
                            Name = "Văn"
                        },
                        new
                        {
                            Id = 3L,
                            Code = "PHYS",
                            Name = "Lý"
                        },
                        new
                        {
                            Id = 4L,
                            Code = "CHEM",
                            Name = "Hoá"
                        },
                        new
                        {
                            Id = 5L,
                            Code = "BIO",
                            Name = "Sinh"
                        },
                        new
                        {
                            Id = 6L,
                            Code = "CNS",
                            Name = "Khoa học tự nhiên"
                        },
                        new
                        {
                            Id = 7L,
                            Code = "HIST",
                            Name = "Sử"
                        },
                        new
                        {
                            Id = 8L,
                            Code = "GEO",
                            Name = "Địa"
                        },
                        new
                        {
                            Id = 9L,
                            Code = "CIV",
                            Name = "Giáo dục công dân"
                        },
                        new
                        {
                            Id = 10L,
                            Code = "CSS",
                            Name = "Khoa học xã hội"
                        },
                        new
                        {
                            Id = 11L,
                            Code = "ENG",
                            Name = "English"
                        });
                });

            modelBuilder.Entity("ManageSchoolScore.Models.Score", b =>
                {
                    b.HasOne("ManageSchoolScore.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ManageSchoolScore.Models.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("ManageSchoolScore.Models.Student", b =>
                {
                    b.HasOne("ManageSchoolScore.Models.SchoolYear", "SchoolYear")
                        .WithMany()
                        .HasForeignKey("SchoolYearId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SchoolYear");
                });
#pragma warning restore 612, 618
        }
    }
}
