// <auto-generated />
using ManageSchoolScore.DatabaseContextMSS;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ManageSchoolScore.Migrations
{
    [DbContext(typeof(DBContextMSS))]
    partial class DBContextMSSModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ManageSchoolScore.Models.SchoolYear", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ExamYear")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SchoolYears");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ExamYear = 2017,
                            Name = "2017",
                            Status = ""
                        },
                        new
                        {
                            Id = 2,
                            ExamYear = 2018,
                            Name = "2018",
                            Status = ""
                        },
                        new
                        {
                            Id = 3,
                            ExamYear = 2019,
                            Name = "2019",
                            Status = ""
                        },
                        new
                        {
                            Id = 4,
                            ExamYear = 2020,
                            Name = "2020",
                            Status = ""
                        },
                        new
                        {
                            Id = 5,
                            ExamYear = 2021,
                            Name = "2021",
                            Status = ""
                        },
                        new
                        {
                            Id = 6,
                            ExamYear = 2022,
                            Name = "2022",
                            Status = ""
                        },
                        new
                        {
                            Id = 7,
                            ExamYear = 2023,
                            Name = "2023",
                            Status = ""
                        },
                        new
                        {
                            Id = 8,
                            ExamYear = 2024,
                            Name = "2024",
                            Status = ""
                        });
                });

            modelBuilder.Entity("ManageSchoolScore.Models.Score", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("ScoreInDecimal")
                        .HasColumnType("float");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.HasIndex("SubjectId");

                    b.ToTable("Scores");
                });

            modelBuilder.Entity("ManageSchoolScore.Models.Statistics", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Biology")
                        .HasColumnType("int");

                    b.Property<int>("Chemistry")
                        .HasColumnType("int");

                    b.Property<int>("CivicEducation")
                        .HasColumnType("int");

                    b.Property<int>("English")
                        .HasColumnType("int");

                    b.Property<int>("Geography")
                        .HasColumnType("int");

                    b.Property<int>("History")
                        .HasColumnType("int");

                    b.Property<int>("Literature")
                        .HasColumnType("int");

                    b.Property<int>("Math")
                        .HasColumnType("int");

                    b.Property<int>("Physics")
                        .HasColumnType("int");

                    b.Property<int>("StudentCount")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Statistics");
                });

            modelBuilder.Entity("ManageSchoolScore.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("SchoolYearId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SchoolYearId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("ManageSchoolScore.Models.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Subjects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "MATH",
                            Name = "Toán"
                        },
                        new
                        {
                            Id = 2,
                            Code = "LIT",
                            Name = "Văn"
                        },
                        new
                        {
                            Id = 3,
                            Code = "PHYS",
                            Name = "Lý"
                        },
                        new
                        {
                            Id = 4,
                            Code = "CHEM",
                            Name = "Hoá"
                        },
                        new
                        {
                            Id = 5,
                            Code = "BIO",
                            Name = "Sinh"
                        },
                        new
                        {
                            Id = 6,
                            Code = "CNS",
                            Name = "Khoa học tự nhiên"
                        },
                        new
                        {
                            Id = 7,
                            Code = "HIST",
                            Name = "Sử"
                        },
                        new
                        {
                            Id = 8,
                            Code = "GEO",
                            Name = "Địa"
                        },
                        new
                        {
                            Id = 9,
                            Code = "CIV",
                            Name = "Giáo dục công dân"
                        },
                        new
                        {
                            Id = 10,
                            Code = "CSS",
                            Name = "Khoa học xã hội"
                        },
                        new
                        {
                            Id = 11,
                            Code = "ENG",
                            Name = "English"
                        });
                });

            modelBuilder.Entity("ManageSchoolScore.Models.TopScore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("KhoiThi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SchoolYear")
                        .HasColumnType("int");

                    b.Property<double>("Score")
                        .HasColumnType("float");

                    b.Property<string>("StudentCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TopScores");
                });

            modelBuilder.Entity("ManageSchoolScore.Models.Score", b =>
                {
                    b.HasOne("ManageSchoolScore.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ManageSchoolScore.Models.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("ManageSchoolScore.Models.Student", b =>
                {
                    b.HasOne("ManageSchoolScore.Models.SchoolYear", "SchoolYear")
                        .WithMany()
                        .HasForeignKey("SchoolYearId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SchoolYear");
                });
#pragma warning restore 612, 618
        }
    }
}
